// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhlpyrksjgtutymqxlxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5obHB5cmtzamd0dXR5bXF4bHh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNzgwNjQsImV4cCI6MjA2MTk1NDA2NH0.o2GXvWT3j90Ef4TtvQWSRd3xKJUIEeDgAs0mLo-AE-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);